apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_dir}}-service
spec:
  selector:
    app: {{cookiecutter.project_dir}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_dir}}-ui-service
spec:
  selector:
    app: {{cookiecutter.project_dir}}-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
